-d Y:\Workspace\SmartChipSystem\e203\fpga_gowin_flow_estimation\impl\gwsynthesis\top.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst Y:\Workspace\SmartChipSystem\e203\fpga_gowin_flow_estimation\src\top.cst
-cfg Y:\Workspace\SmartChipSystem\e203\fpga_gowin_flow_estimation\impl\pnr\device.cfg
-sdc Y:\Workspace\SmartChipSystem\e203\fpga_gowin_flow_estimation\src\lcd.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
