-d F:\schoolwork\chipdesign\codes\own\fpga_gowin_flow_estimation-main\fpga_gowin_flow_estimation-main\impl\gwsynthesis\top.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst F:\schoolwork\chipdesign\codes\own\fpga_gowin_flow_estimation-main\fpga_gowin_flow_estimation-main\src\top.cst
-cfg F:\schoolwork\chipdesign\codes\own\fpga_gowin_flow_estimation-main\fpga_gowin_flow_estimation-main\impl\pnr\device.cfg
-sdc F:\schoolwork\chipdesign\codes\own\fpga_gowin_flow_estimation-main\fpga_gowin_flow_estimation-main\src\lcd.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
