`define MEM_DDR3
`define DEF_ADDR_WIDTH 28
`define SRAM_DATA_WIDTH_128
`define DEF_SRAM_DATA_WIDTH 128
`define DEF_BURST_WRITE_LENGTH 32
`define DEF_BURST_READ_LENGTH 32
`define WR_VIDEO_WIDTH_32
`define DEF_WR_VIDEO_WIDTH 32
`define RD_VIDEO_WIDTH_32
`define DEF_RD_VIDEO_WIDTH 32
`define DEF_IMAGE_SIZE 32'h10000000
`define USE_THREE_FRAME_BUFFER
`define WRITE_FIFO_DEPTH_4096
`define DEF_WRITE_FIFO_DEPTH 4096
`define READ_FIFO_DEPTH_4096
`define DEF_READ_FIFO_DEPTH 4096
`define BURST_NUMBER_ENABLE
